plugin:
    name: 'Spektak'
    description: 'Dashboard for artists work declarations in France'
    author: 'David Ferreira'
    icon: oc-icon-calculator
    homepage: ''
navigation:
    main-menu-item:
        label: Spektak
        url: davindisko/spektak/prestations
        icon: icon-simplybuilt
        sideMenu:
            side-menu-item:
                label: Employeurs
                url: davindisko/spektak/employeurs
                icon: icon-users
            side-menu-item2:
                label: Prestations
                url: davindisko/spektak/prestations
                icon: icon-calendar
