plugin:
    name: 'davindisko.spektak::lang.plugin.name'
    description: 'davindisko.spektak::lang.plugin.description'
    author: 'David Ferreira'
    icon: icon-calendar-o
    homepage: ''
navigation:
    main-menu-item:
        label: Spektak
        url: davindisko/spektak/prestations
        icon: icon-calendar-o
        sideMenu:
            side-menu-item:
                label: 'davindisko.spektak::lang.employers.employers'
                url: davindisko/spektak/employeurs
                icon: icon-users
            side-menu-item2:
                label: 'davindisko.spektak::lang.performances.performances'
                url: davindisko/spektak/prestations
                icon: icon-calendar
