list: $/davindisko/spektak/models/employeur/columns.yaml
modelClass: Davindisko\Spektak\Models\Employeur
title: Employeurs
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'davindisko/spektak/employeurs/update/:id'
