name: Employeurs
form: $/davindisko/spektak/models/employeur/fields.yaml
modelClass: Davindisko\Spektak\Models\Employeur
defaultRedirect: davindisko/spektak/employeurs
create:
    redirect: 'davindisko/spektak/employeurs/update/:id'
    redirectClose: davindisko/spektak/employeurs
update:
    redirect: davindisko/spektak/employeurs
    redirectClose: davindisko/spektak/employeurs
