name: Prestations
form: $/davindisko/spektak/models/prestation/fields.yaml
modelClass: Davindisko\Spektak\Models\Prestation
defaultRedirect: davindisko/spektak/prestations
create:
    redirect: 'davindisko/spektak/prestations/update/:id'
    redirectClose: davindisko/spektak/prestations
update:
    redirect: davindisko/spektak/prestations
    redirectClose: davindisko/spektak/prestations
